I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 58, in script
    python:
  File "game/script.rpy", line 60, in <module>
    opener = urllib2.build_opener(urllib2.HTTPHandler(debuglevel=1))
NameError: name 'urllib2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 58, in script
    python:
  File "C:\Users\rodri\Desktop\renpy-7.2.2-sdk\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\rodri\Desktop\renpy-7.2.2-sdk\renpy\python.py", line 1959, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 60, in <module>
    opener = urllib2.build_opener(urllib2.HTTPHandler(debuglevel=1))
NameError: name 'urllib2' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.0.271
MySQLTest 1.0
Mon Jul 08 17:03:29 2019
