I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 85, in script
    e "[userList2]"
Exception: The displayable with id 'what' was not given the exact contents of the what variable given to the say screen.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 85, in script
    e "[userList2]"
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\ast.py", line 708, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\exports.py", line 1345, in say
    who(what, *args, **kwargs)
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\character.py", line 1142, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\character.py", line 842, in do_display
    **display_args)
  File "E:\Downloads 2\renpy-7.3.5-sdk\renpy\character.py", line 575, in display_say
    raise Exception("The displayable with id 'what' was not given the exact contents of the what variable given to the say screen.")
Exception: The displayable with id 'what' was not given the exact contents of the what variable given to the say screen.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
MySQLTest 1.0
Wed Oct 21 20:59:04 2020
